# See https://ashishnoob.medium.com/configuring-spring-boot-applications-in-kubernetes-e9d6da1c6a3b
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  application.properties: c3ByaW5nLmRhdGFzb3VyY2UudXJsPWpkYmM6bXlzcWw6Ly9tc3FsLXByb2QzMzA2L2RibmFtZQpzcHJpbmcuZGF0YXNvdXJjZS51c2VybmFtZT1kYnVzZXJuYW1lCnNwcmluZy5kYXRhc291cmNlLnBhc3N3b3JkPUZhbmN5UGFzc3dvcmQK
---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: my-container
      image: my-container
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: application-properties
          mountPath: "/opt/unicorn/application.properties"
          readOnly: true
          subPath: application.properties
      
      volumes:
        - name: application-properties
          secret:
            secretName: my-secret
