# See https://medium.com/@martin.hodges/simple-service-for-testing-kubernetes-configurations-189e9409b776
# open sh to pod
# kubectl exec -it nginx-deployment-1-f8cd7f55d-5nsx4 -- sh
# then
# curl http://localhost:80
# undeploy
# kubectl delete -f nginx.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-1
  namespace: default
data:
  index.html: |
    <html>
    <h2>Hello world 1!!</h2>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        testService: service1
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-index-config
              mountPath: /usr/share/nginx/html
      volumes:
        - name: nginx-index-config
          configMap:
            name: nginx-config-1
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
    testService: service-1
  # NodePort provides a way to expose a group of Pods to the outside world. It exposes a port in each Node.
  # When a NodePort is created, kube-proxy exposes a port in the range 30000–32767.
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30081