# See https://medium.com/@danielepolencic/kubernetes-challenge-2-waiting-for-a-miracle-f8448c864397
# After the SIGTERM signal wait for kubernetes components to finally remove the endpoint
apiVersion: v1
kind: Pod
metadata:
  name: graceful-shutdown-example
spec:
  containers:
    - name: sample-container
      image: nginx
      lifecycle:
        preStop:
          exec:
            command: ["/bin/sh", "-c", "nginx -s quit && sleep 30"]