---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-account-blog
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: sa-role-blog
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]