---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: role-binding-blog
  namespace: default
subjects:
  - kind: ServiceAccount
    name: sa-account-blog
    namespace: default
roleRef:
  kind: Role
  name: sa-role-blog
  apiGroup: rbac.authorization.k8s.io