# See https://overcast.blog/5-advanced-techniques-for-kubernetes-autoscaler-optimization-3ef351f487f8
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: custom-metric-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: your-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Pods
      pods:
        metric:
          name: your_custom_metric
        target:
          type: AverageValue
          averageValue: 500m