# See https://overcast.blog/13-kubernetes-tricks-you-didnt-know-647de6364472
# CRDs allow you to extend Kubernetes with your own API objects, enabling the creation of custom resources that operate like native
# Kubernetes objects. This is powerful for adding domain-specific functionality to your clusters, facilitating custom operations, and
# integrating with external systems.

# This CRD defines a new resource type CronTab in the cluster, which can be used to schedule tasks just like a traditional cron job,
# but with Kubernetes-native management.
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: crontabs.stable.example.com
spec:
  group: stable.example.com
  versions:
    - name: v1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: crontabs
    singular: crontab
    kind: CronTab
    shortNames:
      - ct