# pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: example-pv
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  # This PV is intended for file-based storage.
  volumeMode: Filesystem
  # “Retain” means that the PV’s data is retained even if the associated PVC is deleted, and manual cleanup is required.
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  hostPath:
    # To mount volumes using Kubernetes on Docker Desktop for Windows the path will be
    path: /run/desktop/mnt/host/d/myvolume
    # Automatically creates the directory
    type: DirectoryOrCreate