# See https://awsmorocco.com/lessons-learned-from-mounting-secrets-to-pods-on-kubernetes-ac0bbe8bd2ae
# Unlike environment variables, secrets mounted as volumes support dynamic updates without requiring a pod restart.
# The application can detect changes in the mounted files and use the updated data without downtime.

# To test it
# kubectl exec -it my-pod -- sh
# Do
# cat /etc/secrets/password

# File content is mypassword

apiVersion: v1
kind: Secret
metadata:
  name: mydatabase-secret
type: Opaque
data:
  username: bXl1c2Vy          # myuser in base64
  password: bXlwYXNzd29yZA==  # mypassword in base64
---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: my-container
      image: alpine:latest
      imagePullPolicy: IfNotPresent
      command: [ "sh", "-c", "tail -f /dev/null" ]
      volumeMounts:
        - name: secret-volume
          mountPath: /etc/secrets/password
          readOnly: true
          # Allows you to mount only a specific key or file from the secret into a specified path within the container.
          # Changes to the secret key do not automatically propagate to volumes using subPath until the pod is restarted !
          subPath: password
  volumes:
    - name: secret-volume
      secret:
        secretName: mydatabase-secret
