# See https://awsmorocco.com/lessons-learned-from-mounting-secrets-to-pods-on-kubernetes-ac0bbe8bd2ae
# A significant downside is that changes to environment variables require a restart of the pod to take effect.

# To test it
# kubectl exec -it my-pod -- sh
# Do
# echo $USERNAME
# echo $PASSWORD

apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  username: bXl1c2Vy          # myuser in base64
  password: bXlwYXNzd29yZA==  # mypassword in base64
---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: my-container
      image: alpine:latest
      imagePullPolicy: IfNotPresent
      command: [ "sh", "-c", "tail -f /dev/null" ]
      env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: password
